### ISSUE TITLE
Advantages over nWidart Laravel Modules

### ISSUE THREAD

**Issue by AliN11** [InterNACHI/modular#1]
Hi. You are probably familiar with [nWidart Laravel Modules](https://github.com/nWidart/laravel-modules) and I'm interested in knowing the advantages over that. It would be nice to have a comparison. Thanks.

**Comment by inxilpro** [comment]
Laravel Modules is a great package but it has a different focus. As far as I understand, it was built for AsgardCMS as a way to add support for enabling/disabling plugins and supports installing modules from packagist. If you were building something like a CMS that needs plugin support, the nWidart package is a much better fit.

On the other hand, this package is built to have **minimal impact**. It relies on existing Laravel conventions and features rather than adding new ones, which makes it a great low-impact way to introduce modules. If you ever choose to stop using InterNACHI/modular, you can do so with minimal effort.

Both are good packages. Our main reason for not choosing the nWidart project is that it requires that you use somewhat non-standard naming and organization, and has more overhead. The beauty of our solution is that there's **just not much to it** — which makes it easier to maintain and keep in sync with future Laravel releases.

**Comment by inxilpro** [comment]
I also added [a section to the README](https://github.com/InterNACHI/modular#comparison-to-nwidartlaravel-modules) about the pros and cons of each.
